FROM openjdk:17-alpine
WORKDIR /app
COPY target/Model_Full_Stack_Project-0.0.1-SNAPSHOT.jar Model_Full_Stack_Project-0.0.1-SNAPSHOT
EXPOSE 15000
CMD [ "java", "-jar", "Model_Full_Stack_Project-0.0.1-SNAPSHOT" ]